### ISSUE TITLE
TypeScript: missing dependency or peer dependency @types/ws as of 0.15.1

### ISSUE THREAD

**Issue by kevinlul** [abalabahaha/eris#1201]
```
node_modules/eris/index.d.ts:8:28 - error TS7016: Could not find a declaration file for module 'ws'. 'C:/Users/home-dell/Documents/Codespace/eris-bot-template/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

8 import * as WebSocket from "ws";
```

**Comment by HeadTriXz** [comment]
@types/ws is a dev dependency.

**Comment by DonovanDMC** [comment]
Development dependencies are not installed by default, see the [npm install](https://docs.npmjs.com/cli/v7/commands/npm-install) docs

**Comment by bsian03** [comment]
Are you able to provide a copy of your tsconfig here?

**Comment by abalabahaha** [comment]
After some experimenting with @aetheryx we found that this only happens with `skipLibCheck: false` and `noImplicitAny: true` in tsconfig. This error should go away when you set `skipLibCheck: true`, or you can install `@types/ws` as a dev dependency of your application.

Eris will not add `@types/ws` as a required (not dev) dependency to get around the NPM limitation because that doesn't really make sense. The types for `.ws` will probably be removed from the lib in a future release, since usage of this property is extremely rare and unsupported anyway.
