### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by xhyrom** [abalabahaha/eris#1263]
Why is `bot.createMessage`? Is the message created to the bot or to the room? Or why is `bot.createGuildEmoji`? It doesn't make any logic at all to have it in the bot. Why not just `guild.createEmoji` or `guild.emojis.create`?

**Comment by JustCat80** [comment]
Because we try and stick to the documentation and discord has it that way so we do aswell

**Comment by LJNeon** [comment]
> Why is `bot.createMessage`? Is the message created to the bot or to the room?

If you were to properly look at that method, you would see that it has `channelID` as the first argument. At least, I assume that's what you meant by "room", hard to know for sure.

> Or why is bot.createGuildEmoji? It doesn't make any logic at all to have it in the bot. Why not just guild.createEmoji or guild.emojis.create?

Firstly, `guild.createEmoji()` actually [does exist](https://abal.moe/Eris/docs/Guild#method-createEmoji). Secondly, for an issue with "Logic" as the title you sure don't give any particular reasons or well... logic... past the single word "why". Here's some "why"s for you:

Only a guild ID is necessary to create an emoji in a particular server, so why should developers be forced to use the entire `Guild` object?
That method doesn't require the emoji cache to work, so why should it be attached to a cache it doesn't need or use? This seems like a combination of poor design and backwards priorities, and gives me "OOP for the sake of OOP" vibes.

**Comment by Assassin-1234** [comment]
you do realize that Eris is a whole different library and there would be no difference in discord.js and Eris if they legit start changing everything just so discord.js users dont complain? you can pass in guildId in createGuildEmoji function to perform the action

**Comment by xhyrom** [comment]
> you do realize that Eris is a whole different library and there would be no difference in discord.js and Eris if they legit start changing everything just so discord.js users dont complain? you can pass in guildId in createGuildEmoji function to perform the action

Yes, but the point there is that it doesn't make any logic. It can always be done as a djs but also in other ways. Sorry but your `bot.x` is horrible. It might as well be `guild.createEmoji`

**Comment by JustCat80** [comment]
> Yes, but the point there is that it doesn't make any logic. It can always be done as a djs but also in other ways. Sorry but your `bot.x` is horrible. It might as well be `guild.createEmoji`

...[whos gonna tell em](https://abal.moe/Eris/docs/Guild#method-createEmoji)

**Comment by xhyrom** [comment]
> > Why is `bot.createMessage`? Is the message created to the bot or to the room?
> 
> If you were to properly look at that method, you would see that it has `channelID` as the first argument. At least, I assume that's what you meant by "room", hard to know for sure.
> 
> > Or why is bot.createGuildEmoji? It doesn't make any logic at all to have it in the bot. Why not just guild.createEmoji or guild.emojis.create?
> 
> Firstly, `guild.createEmoji()` actually [does exist](https://abal.moe/Eris/docs/Guild#method-createEmoji). Secondly, for an issue with "Logic" as the title you sure don't give any particular reasons or well... logic... past the single word "why". Here's some "why"s for you:
> 
> Only a guild ID is necessary to create an emoji in a particular server, so why should developers be forced to use the entire `Guild` object?
> That method doesn't require the emoji cache to work, so why should it be attached to a cache it doesn't need or use? This seems like a combination of poor design and backwards priorities, and gives me "OOP for the sake of OOP" vibes.



> > Why is `bot.createMessage`? Is the message created to the bot or to the room?
> 
> If you were to properly look at that method, you would see that it has `channelID` as the first argument. At least, I assume that's what you meant by "room", hard to know for sure.
> 
> > Or why is bot.createGuildEmoji? It doesn't make any logic at all to have it in the bot. Why not just guild.createEmoji or guild.emojis.create?
> 
> Firstly, `guild.createEmoji()` actually [does exist](https://abal.moe/Eris/docs/Guild#method-createEmoji). Secondly, for an issue with "Logic" as the title you sure don't give any particular reasons or well... logic... past the single word "why". Here's some "why"s for you:
> 
> Only a guild ID is necessary to create an emoji in a particular server, so why should developers be forced to use the entire `Guild` object?
> That method doesn't require the emoji cache to work, so why should it be attached to a cache it doesn't need or use? This seems like a combination of poor design and backwards priorities, and gives me "OOP for the sake of OOP" vibes.

So as long as the guild.createEmoji() function exists, why is it still in the bot? Do you plan to just add it so people don't have to keep changing it? As well, but then you might have a lot of problems with having duplicate codes and you might end up stopping the semver altogether if you follow it at all.

**Comment by xhyrom** [comment]
> > Yes, but the point there is that it doesn't make any logic. It can always be done as a djs but also in other ways. Sorry but your `bot.x` is horrible. It might as well be `guild.createEmoji`
> 
> ...[whos gonna tell em](https://abal.moe/Eris/docs/Guild#method-createEmoji)

https://github.com/abalabahaha/eris/issues/1263#issuecomment-899212091

**Comment by JustCat80** [comment]
> So as long as the guild.createEmoji() function exists, why is it still in the bot? Do you plan to just add it so people don't have to keep changing it? As well, but then you might have a lot of problems with having duplicate codes and you might end up stopping the semver altogether if you follow it at all.

how eris does things is have client methods, and then have other things run those methods, please shut the fuck up if you dont know what you are talking about.

**Comment by GoldenAngel2** [comment]
1) It's not duplicated code
2) Perhaps actually read the source code before actually making an issue about it. https://github.com/abalabahaha/eris/blob/dev/lib/structures/Guild.js#L371

**Comment by xhyrom** [comment]
> > So as long as the guild.createEmoji() function exists, why is it still in the bot? Do you plan to just add it so people don't have to keep changing it? As well, but then you might have a lot of problems with having duplicate codes and you might end up stopping the semver altogether if you follow it at all.
> 
> how eris does things is have client methods, and then have other things run those methods, please shut the fuck up if you dont know what you are talking about.

And what's the point of cramming 1000 methods into a client and then just running them from another file? It can't just be put into that Guild class? Please, now you think of me as some kind of djs fan but my point here is just that it's pointless to have it that way.

**Comment by JustCat80** [comment]
> And what's the point of cramming 1000 methods into a client and then just running them from another file? It can't just be put into that Guild class? Please, now you think of me as some kind of djs fan but my point here is just that it's pointless to have it that way.

not really, it gives more control to the user

**Comment by xhyrom** [comment]
> > And what's the point of cramming 1000 methods into a client and then just running them from another file? It can't just be put into that Guild class? Please, now you think of me as some kind of djs fan but my point here is just that it's pointless to have it that way.
> 
> not really, it gives more control to the user

By having a billion functions in the client only to be run from another file. Give an example for "more control".

**Comment by eritbh** [comment]
I feel like the most productive thing to do would just be to lock this issue at this point, but I'm bored so I'll give this a shot:

As a design goal, Eris tries to match its provided functions to the available API methods as closely as possible. For things like creating a message, the API request behind the scenes doesn't actually require any information other than a channel ID and the new message content. You don't need all the information about the channel to do this, only the ID of the channel you want to send to. You can even send to channels that the client hasn't cached if you want, as long as the bot is in that channel - this allows you to do things like hardcoding the IDs of important channels as a quick-and-dirty way to configure a small, single-purpose bot. You don't need to fetch the channel's info beforehand, you can just have a channel ID and send a message to that channel without any additional overhead. The API requires nothing more than the channel's ID to create a message in the channel, so there's no reason for Eris to restrict you to creating messages only in channels that it has cached.

Because most API calls are like this, only requiring IDs and not full knowledge of the structures being represented, `client.createMessage()` and other methods on the client itself can be thought of as the "canonical" way to perform these actions in Eris. In fact, [`channel.createMessage(content)` is no more than a helper that maps directly to `client.createMessage(channel.id, content)`](https://github.com/abalabahaha/eris/blob/master/lib/structures/TextChannel.js#L84-L86), and this is true of most API methods on non-Client structures throughout Eris. If you're arguing that convenience wrappers shouldn't exist, and the library should only provide a single way to perform a given action, then it'd be more likely we'd remove the structure helpers than remove the client methods.

Many people are used to programming in an object-oriented style, where calling methods on objects is seen as the most natural way to do things. But the truth is that APIs don't inherently have any concept of object-orientation; an HTTP API is just a collection of routes you can throw data at. Eris provides object-oriented structures and methods for working with the Discord API because it can make many things easier, and it's familiar to many developers - but it doesn't make *all* things easier, and isn't familiar to *all* developers. The "just a bunch of methods on the client" is a structure more closely representing the API itself, which has its own advantages even if you don't leverage them them yourself.
