### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by banocean** [abalabahaha/eris#1282]
Support for Deno runtime

**Comment by DonovanDMC** [comment]
There's no good reason for us to take double the development time to support deno, the smallish community around deno doesn't justify supporting it

And none of our primary contributors (that I know of) actively use deno, so testing would be minimal

**Comment by aqilc** [comment]
I mean prs and forks always available :)

The reason it's not easy is because Deno doesn't have a package registry so we would need to host our own server with like 6k lines bundled to bring proper support, with types in that same file. Integrating types would also take about a month, and that would also need updating separately, and we would need to swap out several apis and libs we currently use. Updating would also be an extreme pain, and there is too little demand for us to go through the effort. "double the development" doesn't nearly explain how much stuff we would need to do. That's why it's only really possible on a fork with maybe a complete rewrite made specially for Deno.

**Comment by banocean** [comment]
> The reason it's not easy is because Deno doesn't have a package registry so we would need to host our own server with like 6k lines bundled to bring proper support, with types in that same file.

https://deno.land/x ?
