### ISSUE TITLE
PCM audio playback got interrupted on Node 20

### ISSUE THREAD

**Issue by jimchen5209** [abalabahaha/eris#1492]
Not sure what's changed in Node 20 to affect this.  

After upgrading Node from 18 to 20, the voice got interrupted at about 200ms when I attempted to play a PCM file, without any error or disconnection.  
It works fine when I play an OPUS file.  
If I downgrade to Node 18, everything works fine again.  

I've tested across Node 18 to 21, it breaks only on version >= 20.  

I've created a repo to reproduce this bug at https://github.com/jimchen5209/eris-node20-bug.

**Comment by jimchen5209** [comment]
After debugging and searching, the problem is at node.js' side.
The issue is https://github.com/nodejs/node/issues/51930.
Fixed by applying workaround `highWaterMark` variable to `1` at [lib/voice/streams/BaseTransformer.js](https://github.com/abalabahaha/eris/blob/dev/lib/voice/streams/BaseTransformer.js) or downgrading node.js to `20.9.0`.

**Comment by bsian03** [comment]
fwiw nodejs/node#53261 which fixes the node bug is merged, in current release 22.4.0. I don't consider this worth fixing in eris since it's only affecting LTS>v20.9 and <22.4 but it's worth noting it down since it is an LTS bug.
For now I'll keep this open since Node22 isn't in LTS just yet.

Thanks for catching this btw

**Comment by bsian03** [comment]
node 22 is now LTS!
