### ISSUE TITLE
Disabling event "GUILD_CREATE" also disables "MESSAGE_CREATE" and possibly other events.

### ISSUE THREAD

**Issue by PikaDude** [abalabahaha/eris#247]
When I disable the GUILD_CREATE event like so, the messageCreate event is never fired.
```
var bot = new Eris(redacted, {
    disableEvents: {
        GUILD_CREATE: true,
        MESSAGE_CREATE: false
    }
});
bot.on('ready', () => {
	console.log('Ready!');
});
bot.on('messageCreate', (message) => {
	console.log(message.content);
});
```
I have also tried this with the channelCreate event and this, too, does not work if Guild Create is disabled. I am not sure if this is intended and I believe that this should be revised as disabling the "bot joined a guild" event should not conflict with any other event.

**Comment by abalabahaha** [comment]
"should be revised" kek

This is probably happening because the lib cannot populate the channel cache. GUILD_CREATE contains guild data, including data for the channels in the guild, so disabling that causes the lib to not know the guild's channels exist. Since the lib requires the channel to be cached for `Message.channel`, it fails to create the Message object, so the event isn't fired.

All the lib does is disable processing for disabled events from Discord. Hence why the event names in disabledEvents are weird, since they're straight from the Discord gateway. There is nothing the lib can do about caches not being filled due to an event not being processed.

I could alter the lib to make `Message.channel` a getter and removing the hard dependency on the channel cache, but that would break a lot of code depending on `Message.channel` always existing, so that is not a decision to be made anytime soon.

**Comment by PikaDude** [comment]
If that is the case, maybe you should change the description of the event in the Eris docs, as it says:

>GUILD_CREATE - bot joined a guild

as it doesn't seem to match with what you just told me.

**Comment by abalabahaha** [comment]
When initializing the connection, the bot gets a GUILD_CREATE for every guild it is in. Maybe I'll add a note to clarify the boot sequence, but that description is technically correct.
