### ISSUE TITLE
editChannel depends on channel cache

### ISSUE THREAD

**Issue by MichaelTheriot** [abalabahaha/eris#262]
I'm trying to create a voice channel with a user limit.

```js
const createVoice = async function (name, userLimit = 2) {
  const guild = bot.guilds.get(guildID);
  const channel = await guild.createChannel(name, 2);
  await channel.edit({userLimit});
  return channel;
};
```

This is throwing the following error:
```
Error: Channel <id> not found
```

From what I can tell `guild.channels` does not yet have an entry for `channel.id` and thus causes the error.

Reproduce:

```js
const Eris = require('eris');
const bot = new Eris(token);

bot.on('shardReady', async function () {
  const guild = bot.guilds.get(guildID);
  const channel = await guild.createChannel('test');
  console.log(guild.channels.has(channel.id));
});

bot.connect();
```

Several runs:
```
true
false
false
false
```

**Comment by abalabahaha** [comment]
The behavior you described as a bug is intended; the cache is controlled by websocket events and not REST calls, because updating the cache twice would cause collisions and add some complication to event emitting. The websocket event may arrive before or after the REST call resolves, so code in createXXX() calls should depend on the resolved object and not the cache.

However, editChannel() shouldn't have a hard dependency on the cache. This is probably due to old code from when Discord's PATCH code had inconsistency issues, and should be updated to remove the hard dependency. I've updated the issue to reflect this.

**Comment by abalabahaha** [comment]
Apparently this was already fixed in dev... Should land in a release sometime in the next week.
