### ISSUE TITLE
voiceStateUpdate not being parsed by lib

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#367]
I currently have a problem with the bot. When I join a voice channel, the voice data within the GuildMember class does not update, as you can see from the image below.

![image](https://user-images.githubusercontent.com/16949253/36821358-4a962180-1cb8-11e8-9e1b-e98f9af986cd.png)

Here's a picture of what `channelID` looks like after I join the voice channel:

![image](https://user-images.githubusercontent.com/16949253/36821402-792b86d4-1cb8-11e8-9d7e-605acfb906db.png)

I don't know what causes this. If it matters, I am using Lavalink with the `eris-lavalink` module. Thanks!

**Comment by auguwu** [comment]
I feel like;
   * Before the voiceStatusUpdate fires; Eris should automatically just fire it in the `bot.on` when it's emitted
   * Maybe it got glitchy and it said it was in a VoiceChannel; so it automatically emitted to the voiceState functionality (We all know that Discord gets glitched since Eris goes get's it's data from the Discord API (if you didn't know lol))

**Comment by PassTheMayo** [comment]
![image](https://user-images.githubusercontent.com/16949253/36825025-f450ca42-1cca-11e8-9d29-ddffa43441af.png)

**Comment by PassTheMayo** [comment]
Turns out I had the event disabled this entire time ;-;
