### ISSUE TITLE
Consider returning voiceConnection only when it's ready

### ISSUE THREAD

**Issue by devoxin** [abalabahaha/eris#381]
When using `await bot.joinVoiceChannel(channelId)`, a voiceConnection is returned but sometimes if the bot/Discord is lagging behind a bit and the bot attempts to play something to the voiceConnection, sometimes it throws:
```
Error: Not ready yet
    at VoiceConnection.play (/home/user/bot/node_modules/eris/lib/voice/VoiceConnection.js:441:19)
```

Perhaps it's worth only returning a voiceConnection upon `ready` being set to true?

**Comment by MoordMachineYT** [comment]
You could also just set up a cooldown from 2 seconds and play it then, the connection object doesn’t have a ready property for no reason.

**Comment by devoxin** [comment]
I'm fully aware.

As for the cooldown, that can lead to:
- Unnecessary delay before playing OR
- Still the same issue depending on how long it takes before the voiceconnection becomes ready

I also believe that to not return a voiceconnection when it's ready might lead to user confusion (as per what's happened here)

**Comment by abalabahaha** [comment]
Considering [this already happens](https://github.com/abalabahaha/eris/blob/e5274091aa42e07d23b67a47a107ea1ebeacaccd/lib/voice/VoiceConnectionManager.js#L27) and has happened [since last year](https://github.com/abalabahaha/eris/commit/ccb14a96b0b998330aab21f012a9a0ac69062597)... Check your Eris version, make sure you’re not calling disconnect somewhere, make sure Discord’s not disconnecting you, etc.

Also don’t do the cooldown thing, it’s bad practice to timeout something that takes a random amount of time.

**Comment by devoxin** [comment]
Using Eris 0.8.5, stream playback is attempted as soon as the bot joins a voicechannel which I believe no disconnects should be encountered in between

**Comment by abalabahaha** [comment]
Going to close this for now, join the Discord channel in the README so we can figure stuff out.
