### ISSUE TITLE
Update to Node v8

### ISSUE THREAD

**Issue by Brayzure** [abalabahaha/eris#402]
It's about time, right?

**Major Additions Between v4 and v8**
- async/await
- classes (whoops, we already use them)
- rest parameters
- spread operator
- destructuring

**Minor Additions**
- default function parameters
- Array.includes()
- Object.values

Now that we have these additional options, what do we want to actually change in the project? Using async/await where possible seems like an all-around good idea, but other changes may have tradeoffs that deserve discussion (`Array.includes()` vs `!Array.indexOf()`, for example).

**Comment by LJNeon** [comment]
I hadn't run benchmarks on `Array#includes` vs `Array#indexOf` for a long time, and it turns out `Array#includes` is now much faster (~10x faster). 

However strict equality (`=== false` compared to like `!`) is indeed still faster abeit not by a large margin. (2-10% varying) I believe that while 2-10% isn't a large speedup, the sheer amount of times it would apply (every single condition lol) add up to a substantial amount.

**Comment by LJNeon** [comment]
And would eris even have a use for rest parameters or the spread operator? As far as I can tell there would be no use for either of them.

**Comment by LJNeon** [comment]
Also using a `for...in` loop to get object values is ~17x faster than `Object#values`, and ~1.5x faster than `Object#keys`. (tested in latest version of node 10)
