### ISSUE TITLE
Filter CommandClient reaction button responses

### ISSUE THREAD

**Issue by lewisakura** [abalabahaha/eris#429]
The current implementation of the CommandClient's reaction buttons allows anyone to react to them and execute that button's method, even if it wasn't the person who executed the command in the first place.

Also, issue 429. I've been ratelimited.

**Comment by AlekEagle** [comment]
If you want to fix this, what you can do is simply store the users ID who executed the command, and upon every reaction button(s) action, check if the user who created the command is the one using the reaction button(s). If you don't like that solution, you can either create a whole new reaction button function, or rewrite the function itself.

**Comment by lewisakura** [comment]
What about type: “cancel” buttons?

________________________________

**Comment by AlekEagle** [comment]
This is where I would say go and edit and change the function itself in the CommandClient. Simply get the user ID who sent the message, either from msg.author.id or msg.member.id, (though I would recommend using msg.author.id since it wouldn't error when used in a DM channel), and check it against the user using the reaction.
