### ISSUE TITLE
Calling addRole on member fetched with guild.getRESTMember fails.

### ISSUE THREAD

**Issue by macdja38** [abalabahaha/eris#479]
Minimal test case
```
      const member = await guild.getRESTMember(" a user ID");
      await member.addRole("a Role ID", "Reason");
```

Error
```
TypeError: Cannot read property 'shard' of null
    at Member.addRole (\eris\lib\structures\Member.js:155:27)
    at toggleRole (\bot\lib\bot.js:83:20)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by eritbh** [comment]
Seems to be caused by passing `null` for the guild argument to `new Member()` from inside `Client#getRESTGuildMember` here: https://github.com/abalabahaha/eris/blob/master/lib/Client.js#L1899

Would this be fixed by using `this.guilds.get(guildID) || null` instead of just `null`?

The same error also exists on the `getRESTGuildMembers`

**Comment by abalabahaha** [comment]
Dupllicate of #418
