### ISSUE TITLE
Default prefix is being replaced by guild prefix?

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#509]
Setting `CommandClient.commandOptions.prefix` supposed to be default prefix right?
After using `CommandClient.registerGuildPrefix(...)` the setting that has been set in `CommandClient.commandOptions.prefix` is being replaced, is this expected behaviour?
For example:
I have `@mention` set in `CommandClient.commandOptions.prefix` so I want it to be default prefix and always available but after updating guild prefix using `CommandClient.registerGuildPrefix(...)` bot doesn't respond to `@mention` anymore.

**Comment by eritbh** [comment]
This is intended behavior as far as I'm aware. If you want to respond to some prefix in addition to the guild-specific one, pass an array of prefix strings to `registerGuildPrefix`.

Check out the Discord channel linked in the readme if you have more questions - it's usually a better place for support than Github issues.

**Comment by ghost** [comment]
> This is intended behavior as far as I'm aware. If you want to respond to some prefix in addition to the guild-specific one, pass an array of prefix strings to `registerGuildPrefix`.
> 
> Check out the Discord channel linked in the readme if you have more questions - it's usually a better place for support than Github issues.

Hm, so I always need to pass an array with my default prefix? Isn't it better and supposed to extend the array of default prefixes with the one that is being passed with `registerGuildPrefix`?

**Comment by eritbh** [comment]
It's not supposed to apply in addition to the default one, since there are also valid use cases for *not* keeping the default when you add a prefix for another guild. If the default is pretty much anything other than a mention, you probably don't want that *or* your custom guild one both triggering commands, since one of the problems that having custom prefixes fixes is having multiple bots respond to the same prefix.

Regardless, this isn't behavior that can be easily changed without breaking backwards compatibility., and the command client isn't very well supported to begin with.

**Comment by ghost** [comment]
> It's not supposed to apply in addition to the default one, since there are also valid use cases for _not_ keeping the default when you add a prefix for another guild. If the default is pretty much anything other than a mention, you probably don't want that _or_ your custom guild one both triggering commands, since one of the problems that having custom prefixes fixes is having multiple bots respond to the same prefix.
> 
> Regardless, this isn't behavior that can be easily changed without breaking backwards compatibility., and the command client isn't very well supported to begin with.

Got it, thank you.
