### ISSUE TITLE
Heartbeat Acknowledgement Failing, Causing Reconnect

### ISSUE THREAD

**Issue by hqnna** [abalabahaha/eris#921]
Multiple bots using the library have been experiencing issues with at a set interval the shards/bot 
will disconnect, and then reconnect a short moment later with the error:

```
Server didn't acknowledge previous heartbeat, possible lost connection
```

At first I thought it was an issue with the recent issue on the api repository with exit codes killing sessions, as seen here: discord/discord-api-docs/issues/1472, however looking into the code base the only use of the code `1000` is in the shard disconnect, however with changing said code, the issue remains.

A screenshot of said issue can be seen as follows:
![screenshot](https://cdn.discordapp.com/attachments/697489244649816084/704138542552580116/unknown.png)

**Comment by motoenduroboy** [comment]
Started listening to the debug event and logging it
![Capture 1](https://user-images.githubusercontent.com/8674282/80328733-8ca5f080-8883-11ea-83c9-1273689e3468.png)
It seems eris will continue to try to immediately reconnect infinite amount of times, I decided to let it run in this state a little more to see if that was the case, I stopped it at attempt 16
![Capture 2](https://user-images.githubusercontent.com/8674282/80328738-8e6fb400-8883-11ea-9534-b864a437ce95.PNG)

**Comment by abalabahaha** [comment]
Eris version/branch?

Have you confirmed that _while_ this is happening, you are still able to establish a connection with Discord via other means?

**Comment by hqnna** [comment]
Latest (Eris 0.12.0), connecting with discord.js and discord.py are both fine and don't seem to have this issue. I can connect with the normal discord client fine so it's not a connection issue.

**Comment by abalabahaha** [comment]
I'll see if I can reproduce it, haven't been able to for any of these connection issue reports so something's clearly missing here...

Also do want to point out that heartbeat timeouts and other library-initiated reconnects [use the code 2 lines above](https://github.com/abalabahaha/eris/blob/27bb9cd02ae990606ab50b32ac186da53d8ca45a/lib/gateway/Shard.js#L100) the [close(`1000`) that people love pointing to](https://github.com/abalabahaha/eris/blob/27bb9cd02ae990606ab50b32ac186da53d8ca45a/lib/gateway/Shard.js#L102), and seems to have been working fine since that chunk of code was written about 3.5 years ago. The "Discord Bots" and "Discord Developers" servers have never been, and never will be, reliable sources of information regarding this library.

**Comment by ak-s** [comment]
After several days of testing with wireshark, I can say that 1006 error loop is caused by Discord. Sometimes the gateway closes the connection immediately (TCP FIN) in response to a Resume packet. I tried closing with code 4901 vs termination, various delays before reconnecting or before sending Resume and Heartbeat packets, nothing helps. I think https://github.com/abalabahaha/eris/commit/da240591e7504075a24ae8d8e0318c79ded9b90a workaround is enough.

**Comment by abalabahaha** [comment]
@ak-s Thank you for investigating :D 

Sounds really odd, but it does somewhat match the logs I've received. Looks like I might have to reach out to more people, but it's interesting how Eris seemingly is the only library hitting this error...

Don't have to answer them all, but I'm curious: So the pcap says that the server initiated the disconnect? Did you notice anything weird from the client (e.g. misplaced/missing ACKs that shouldn't happen under low-bandwidth conditions), or extra data flowing in/out? Only happens in response to the Resume packet, and not the Heartbeat packet? What datacenter/OS/net-hardware (or multiple) have you been testing from, and/or what Cloudflare colo ([https://discord.com/cdn-cgi/trace](https://discord.com/cdn-cgi/trace)) are you hitting?

**Comment by ak-s** [comment]
![reconnect](https://user-images.githubusercontent.com/22549784/81702035-74cd8f80-9473-11ea-9102-1034354a560a.png)
Decrypted TLS:
```
342 {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-main-bgx4\",{\"micros\":0.0}]"]}}
344 {"op":1,"d":7}
346 {"t":null,"s":null,"op":11,"d":null}
348 {"op":6,"d":{"token":"Bot <token>","session_id":"6423069b4feca31ea29620ffabd0ea76","seq":7}}
```
Added testing timeout 1000 ms before sending Resume (348), so Heartbeat (344) goes first.
Response deltas:
344->345-346: 29 ms [ACK] + 153 ms ws reply - Heartbeat OK
348->349-350: 30 ms [ACK] + 158 ms [FIN, ACK] - Resume FAIL

Tested from home :) CF colo=ARN

**Comment by abalabahaha** [comment]
0.13.1 has workarounds for the change in Discord gateway behavior.

**Comment by Wreeper** [comment]
Still happening as of now and i am able to log in just fine.

**Comment by bsian03** [comment]
Whatever it is, your issue doesn't relate to this. Please join our [support server](https://discord.gg/eris) for assistance
